name: single-cell
channels: 
  - conda-forge 
  - bioconda
  - paul.martin-2
  - bu_cnio 
  - r 
dependencies: 
  - r-base
  - r-seurat 
  - r-enrichr
  - r-tidyverse
  - r-ggplot2
  - r-devtools
  - r-ggpubr
  - r-matrix